### ISSUE TITLE
Harden your GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-OlenaEfymenko#1]
Enable 2FA:
* [x] Proceed at https://github.com/settings/security#two-factor-summary
* [x] I recommend using the following TOTP code generator: https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus&hl=en_US
  * If you've got a Bitwarden subscription or a FIDO 2 key — it's even better, but not mandatory for this task. You can get a cheap one using a CloudFlare+Yubikey deal valid until the end of 2022 using this guide: https://www.reddit.com/r/yubikey/comments/xrcly7/cloudflare_deal_for_1011_keys/.
  * Don't forget to _securely_ store the recovery codes

**Comment by OlenaEfymenko** [comment]
done

**Comment by webknjaz** [comment]
Verified, closing.
