### ISSUE TITLE
Configure pre-commit tool for this repo

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-OlenaEfymenko#12]
> # Rules:
> 1. **DO NOT** commit to the `main` branch directly. ever.
> 2. **ABSOLUTELY NO** force pushes allowed for public non-feature branches.
> 3. For every feature, create a new branch matching name `features/<issue-number>-<feature-name>`.
> 4. Submit every feature by creating Pull Request @ github, after that wait for review, fix issues, repeat until approved. If needed rebase the branch on top of main and re-push force it.

  * [x] **I HAVE READ AND UNDERSTOOD THE RULES ABOVE**
------------

* [x] Install `pre-commit` locally as follows:
```console
python3.11 -m pip install pre-commit --user
python3.11 -m pre_commit install
```
* [x] Create branch called `features/12-pre-commit-integration`
* [x] Add [`.pre-commit-config.yaml`](http://pre-commit.com/) config, containing the following [hooks](http://pre-commit.com/hooks.html):
  * [x] no-commit-to-branch
  * [x] [add-trailing-comma](https://github.com/asottile/add-trailing-comma)
  * [x] [remove-tabs](https://github.com/Lucas-C/pre-commit-hooks)
  * [x] trailing-whitespace
  * [x] check-merge-conflict
  * [x] double-quote-string-fixer
  * [x] requirements-txt-fixer
  * [x] check-yaml
  * [x] check-docstring-first
  * [x] end-of-file-fixer
  * [x] name-tests-test
  * [x] check-ast
  * [x] debug-statements
  * [x] flake8
  * [x] [pydocstyle](http://www.pydocstyle.org/en/5.0.1/usage.html#usage-with-the-pre-commit-git-hooks-framework)
  * [x] `pylint` using "local" mode
  * [x] [mypy](https://github.com/pre-commit/mirrors-mypy.git)
* [x] Check repo using command `pre-commit run --all-files`, fix all issues and commit fixes as well
* [x] Create PR with this branch

**Comment by OlenaYefymenko** [comment]
@webknjaz 
After execution command `python3.11 -m pip install pre-commit --user`, the following warning was received:

```
  WARNING: The script pre-commit is installed in '/home/olenayefymenko/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
Can I just ignore this warning? 
In some recommendations, I found a solution: `export PATH=$HOME/.local/bin:$PATH`
But I should use this variant: `export PATH=$PYENV_ROOT/bin:$PATH` for switching between versions

**Comment by webknjaz** [comment]
You can add the former to your zshrc file, additionally to the pyenv one. It prepends said path to the search paths. If not, you won't be able to invoke scripts installed in `~/.local/bin` by their names (like `pre-commit`), though if they implement the runpy interface, you can still invoke (or import) them through the python interpreter (like `python -m pre_commit`).
