### ISSUE TITLE
Replace `pydocstyle` with `flake8-docstrings` in the `pre-commit` check

### ISSUE THREAD

**Issue by OlenaYefymenko** [kpi-web-guild/django-girls-blog-OlenaEfymenko#23]
Replace `pydocstyle` with `flake8-docstrings` in the `pre-commit` check

**Comment by webknjaz** [comment]
It'd be helpful to have something specific in the title and description.

**Comment by webknjaz** [comment]
pydocstyle -> flake8-docstrings
