### ISSUE TITLE
Create an SSH key and add it to GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-OlenaEfymenko#3]
> Note: it's best to complete this task from within the dev environment created in #2

See:
* https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key (you may omit adding a password)
* https://help.github.com/articles/connecting-to-github-with-ssh/

After completing instructions, post the result of the following command in a comment to this issue:
```shell
ssh -T git@github.com
```

Check yourself
--------------

If performed correctly, you'll see your GitHub username in the console output.

**Comment by OlenaEfymenko** [comment]
Святослав, привіт!
Після  фінальної команди  в консолі "ssh -T git@github.com"
отримала таке повідомлення  "Hi OlenaEfymenko! You've successfully authenticated, but GitHub does not provide shell access".
Підкажи, будь ласка, не такий результат повинен бути після перевірки додавання ключа в Github?

**Comment by OlenaEfymenko** [comment]
здається зрозуміла як вирішити проблему, спробую

**Comment by webknjaz** [comment]
That is the correct outcome. Closing.
