### ISSUE TITLE
Create an empty commit on `main` (and push nothing else there!)

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-OlenaEfymenko#5]
The following snippet should help you, given that you're starting with a fresh repository that does not have any commits yet.
```console
git commit --allow-empty -m 'Initial commit'
git push origin main
```

Upon the completion of the task, here are the expectations:
1. Only 1 _(one)_ single commit in the `main` branch.
2. The commit is supposed not to add (or remove for that matter) any files at all.
3. There should be 0 _(zero)_ files appearing in the repository at this point.

P.S. It's best to do this task having read the first 3 chapters of the ProGit 2 book from #4.
P.P.S. Fixing an incorrectly created commit would require amending it, or making an interactive rebase. This may imply going through more materials from #4, googling and/or using StackOverflow.

**Comment by OlenaYefymenko** [comment]
Hello, Sviatoslav! I completed this issue.
Link to repo https://github.com/OlenaYefymenko/learn_git

**Comment by webknjaz** [comment]
@OlenaYefymenko you need to complete it in this repository, not a separate one.

**Comment by OlenaYefymenko** [comment]
@webknjaz ок, done in this repository.

**Comment by webknjaz** [comment]
Brilliant! I've applied the branch protection and pushing to main directory is now forbidden. All the following repository changes are to be made through topic branches and pull requests.
